branches:
  only:
    - source
sudo: false
language: node_js
node_js:
  - 12.9.0
before_script:
  - git config --global user.name 'stvvt'
  - git config --global user.email 'stefan.bg@gmail.com'
  - sed -i "s/GITHUB_TOKEN/${GITHUB_TOKEN}/" _config-travis.yml
script:
  - npm install
  - npm run generate
after_script:
  - npm run deploy -- --config _config.yml,_config-travis.yml
