version: '2'

services:

  blog:
    image: node:12.9.0
    working_dir: /app
    volumes:
      - ./:/app/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    user: "1000"
    ports:
      - "4000:4000"
    command: npm start